Content:
Used Cars Prices

Here you find 78612 records about used cars:
<br>
60 Brand, 382 Model, 33 Modelyear,
<br>
1839 CarModel, 1397 AveragePrice,
<br>
893 MinimumPrice, 916 MaximumPrice,
<br>
over 128 Months/Year.

### Some Questions you should ask yourself about.
1.  Is there any duplicates? .
2. What about the nulls?.
3. Does all columns has the a correct format in its values? if its not how should you make it better?
4. Datatypes?
5. Before starting , after seeing some info about the dataset and from the first look on the dataset , what columns you think will not be necessary in our dataset? (io: what columns you think dropping it will be better?).
<br>
<br>
feel free to wirte only their names in the next cell

Double Click here to start writing

In [40]:
#import Libraries (numpy & Pandas)
import pandas as pd
import numpy as np

In [41]:
#read Data
data=pd.read_csv("used_car_prices.csv")

In [42]:
#print the first 8 row
data.head(8)

,web-scraper-order,Car Model,Month/Year,Average price,Minimum price,Maximum price
0,1680204632-1,Skoda Octavia A8 2022,2023-03,"967,000 EGP","926,000 EGP","1,017,000 EGP"
1,1680204632-2,Skoda Octavia A8 2022,2023-02,"979,000 EGP","931,000 EGP","1,045,000 EGP"
2,1680204632-3,Skoda Octavia A8 2022,2023-01,"917,000 EGP","893,000 EGP","950,000 EGP"
3,1680204632-4,Skoda Octavia A8 2022,2022-12,"881,000 EGP","793,000 EGP","950,000 EGP"
4,1680204632-5,Skoda Octavia A8 2022,2022-11,"868,000 EGP","789,000 EGP","950,000 EGP"
5,1680204632-6,Skoda Octavia A8 2022,2022-10,"797,000 EGP","789,000 EGP","808,000 EGP"
6,1680204632-7,Skoda Octavia A8 2022,2022-09,"837,000 EGP","770,000 EGP","874,000 EGP"
7,1680204632-8,Skoda Octavia A8 2022,2022-08,"779,000 EGP","722,000 EGP","855,000 EGP"

In [43]:
#print the shape Like (There are 84548 rows and 22 columns)
print("There are {} rows and {} colums in this dataset. \n".format(data.shape[0],data.shape[1]))

There are 79090 rows and 6 colums in this dataset.

In [44]:
# try seeing some information about the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79090 entries, 0 to 79089
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   web-scraper-order  79090 non-null  object
 1   Car Model          79090 non-null  object
 2   Month/Year         78612 non-null  object
 3   Average price      78612 non-null  object
 4   Minimum price      78612 non-null  object
 5   Maximum price      78612 non-null  object
dtypes: object(6)
memory usage: 3.6+ MB

In [45]:
# show the number of duplicates here
data.duplicated().sum()

0

In [46]:
# show number of nulls
data.isnull().sum()

web-scraper-order      0
Car Model              0
Month/Year           478
Average price        478
Minimum price        478
Maximum price        478
dtype: int64

In [80]:

# updated the column names Like(To Start with Upper Litter)
aa={}
for i in list(data.columns):
  aa[i] = i.capitalize()
data.rename(columns={'Web-scraper-order': 'Web-scraper-order', 'Car model': 'Car model', 'Month/year': 'Month/year', 'Average price': 'Average price', 'Minimum price': 'Minimum price', 'Maximum price': 'Maximum price'}
, inplace=True)
data.head()

,Web-scraper-order,Car model,Month/year,Average price,Minimum price,Maximum price
0,1680204632-1,Skoda Octavia A8 2022,2023-03,"967,000 EGP","926,000 EGP","1,017,000 EGP"
1,1680204632-2,Skoda Octavia A8 2022,2023-02,"979,000 EGP","931,000 EGP","1,045,000 EGP"
2,1680204632-3,Skoda Octavia A8 2022,2023-01,"917,000 EGP","893,000 EGP","950,000 EGP"
3,1680204632-4,Skoda Octavia A8 2022,2022-12,"881,000 EGP","793,000 EGP","950,000 EGP"
4,1680204632-5,Skoda Octavia A8 2022,2022-11,"868,000 EGP","789,000 EGP","950,000 EGP"

In [90]:
# Split Car Full Data into Brand, Model, And Year of The Model
data[['Brand', 'Model', 'Year']] = data['Car model'].str.split(' ', 2, expand=True)
# data[['Model', 'Year']] = data['Model'].str.split(' ', 2, expand=True)
data

<ipython-input-90-f7c10fef81c9>:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  data[['Brand', 'Model', 'Year']] = data['Car model'].str.split(' ', 2, expand=True)

,Web-scraper-order,Car model,Month/year,Average price,Minimum price,Maximum price,Brand,Model,Year
0,1680204632-1,Skoda Octavia A8 2022,2023-03,"967,000 EGP","926,000 EGP","1,017,000 EGP",Skoda,Octavia,A8 2022
1,1680204632-2,Skoda Octavia A8 2022,2023-02,"979,000 EGP","931,000 EGP","1,045,000 EGP",Skoda,Octavia,A8 2022
2,1680204632-3,Skoda Octavia A8 2022,2023-01,"917,000 EGP","893,000 EGP","950,000 EGP",Skoda,Octavia,A8 2022
3,1680204632-4,Skoda Octavia A8 2022,2022-12,"881,000 EGP","793,000 EGP","950,000 EGP",Skoda,Octavia,A8 2022
4,1680204632-5,Skoda Octavia A8 2022,2022-11,"868,000 EGP","789,000 EGP","950,000 EGP",Skoda,Octavia,A8 2022
...,...,...,...,...,...,...,...,...,...
79085,1680204632-79086,Lada 2107 1991,2018-08,"30,000 EGP","26,000 EGP","33,000 EGP",Lada,2107,1991
79086,1680204632-79087,Lada 2107 1991,2018-07,"33,000 EGP","32,000 EGP","35,000 EGP",Lada,2107,1991
79087,1680204632-79088,Lada 2107 1991,2018-01,"28,000 EGP","25,000 EGP","30,000 EGP",Lada,2107,1991
79088,1680204632-79089,Lada 2107 1991,2017-12,"27,000 EGP","25,000 EGP","28,000 EGP",Lada,2107,1991
79089,1680204632-79090,Lada 2107 1991,2016-03,"24,000 EGP","23,000 EGP","26,000 EGP",Lada,2107,1991

In [101]:
# @title Default title text
# Convert Average price, Minimum price, Maximum price to Numaarical Values
data['Average price'] = data['Average price'].str.replace('EGP', '')
data['Average price'] = data['Average price'].str.replace(',', '')
data['Average price'] = data['Average price'].astype(float)
data['Average price']

0        967000.0
1        979000.0
2        917000.0
3        881000.0
4        868000.0
           ...
79085     30000.0
79086     33000.0
79087     28000.0
79088     27000.0
79089     24000.0
Name: Average price, Length: 79090, dtype: float64

In [102]:
data['Minimum price'] = data['Minimum price'].str.replace('EGP', '')
data['Minimum price'] = data['Minimum price'].str.replace(',', '')
data['Minimum price'] = data['Minimum price'].astype(float)
data['Minimum price']

0        926000.0
1        931000.0
2        893000.0
3        793000.0
4        789000.0
           ...
79085     26000.0
79086     32000.0
79087     25000.0
79088     25000.0
79089     23000.0
Name: Minimum price, Length: 79090, dtype: float64

In [103]:
data['Maximum price'] = data['Maximum price'].str.replace('EGP', '')
data['Maximum price'] = data['Maximum price'].str.replace(',', '')
data['Maximum price'] = data['Maximum price'].astype(float)
data['Maximum price']

0        1017000.0
1        1045000.0
2         950000.0
3         950000.0
4         950000.0
           ...
79085      33000.0
79086      35000.0
79087      30000.0
79088      28000.0
79089      26000.0
Name: Maximum price, Length: 79090, dtype: float64

In [104]:
# Split Month/Year Column to Year and Month
data[['Year', 'Month']] = data['Month/year'].str.split('-', 1, expand=True)
data

<ipython-input-104-97b97bc63344>:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  data[['Year', 'Month']] = data['Month/year'].str.split('-', 1, expand=True)

,Web-scraper-order,Car model,Month/year,Average price,Minimum price,Maximum price,Brand,Model,Year,Month
0,1680204632-1,Skoda Octavia A8 2022,2023-03,967000.0,926000.0,1017000.0,Skoda,Octavia,2023,03
1,1680204632-2,Skoda Octavia A8 2022,2023-02,979000.0,931000.0,1045000.0,Skoda,Octavia,2023,02
2,1680204632-3,Skoda Octavia A8 2022,2023-01,917000.0,893000.0,950000.0,Skoda,Octavia,2023,01
3,1680204632-4,Skoda Octavia A8 2022,2022-12,881000.0,793000.0,950000.0,Skoda,Octavia,2022,12
4,1680204632-5,Skoda Octavia A8 2022,2022-11,868000.0,789000.0,950000.0,Skoda,Octavia,2022,11
...,...,...,...,...,...,...,...,...,...,...
79085,1680204632-79086,Lada 2107 1991,2018-08,30000.0,26000.0,33000.0,Lada,2107,2018,08
79086,1680204632-79087,Lada 2107 1991,2018-07,33000.0,32000.0,35000.0,Lada,2107,2018,07
79087,1680204632-79088,Lada 2107 1991,2018-01,28000.0,25000.0,30000.0,Lada,2107,2018,01
79088,1680204632-79089,Lada 2107 1991,2017-12,27000.0,25000.0,28000.0,Lada,2107,2017,12
79089,1680204632-79090,Lada 2107 1991,2016-03,24000.0,23000.0,26000.0,Lada,2107,2016,03

In [108]:
# let's start with (Average price ,Minimum price ,Maximum price ) , see the number of nulls in them , replace these nulls with the ( mean , median and mode) of these columns
#and in the end check that there are not nulls in data
null_counts = data[['Average price', 'Minimum price', 'Maximum price']].isnull().sum()
print("Number of null values in each column:")
print(null_counts)

mean_values = data[['Average price', 'Minimum price', 'Maximum price']].mean()
median_values = data[['Average price', 'Minimum price', 'Maximum price']].median()
mode_values = data[['Average price', 'Minimum price', 'Maximum price']].mode().iloc[0]  # mode() returns a DataFrame

data['Average price'].fillna(mean_values['Average price'], inplace=True)
data['Minimum price'].fillna(median_values['Minimum price'], inplace=True)
data['Maximum price'].fillna(mode_values['Maximum price'], inplace=True)


null_counts = data[['Average price', 'Minimum price', 'Maximum price']].isnull().sum()
print("Number of null values in each column:")
print(null_counts)

Number of null values in each column:
Average price    478
Minimum price    478
Maximum price    478
dtype: int64
Number of null values in each column:
Average price    0
Minimum price    0
Maximum price    0
dtype: int64